version: "3.1"
services:
  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "8081:8081"
    volumes:
      - ./checkout:/checkout # for config read
  loms:
    image: loms
    build: ./loms/
    ports:
      - "8082:8082"
    volumes:
      - ./loms:/loms  # for config read
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
