token: "secret"
dsn: "host=localhost port=5433 user=checkout password=password dbname=checkout-db sslmode=disable"
services:
  checkout: ":8081"
  loms: "loms:8082"
  product_service: "route256.pavl.uk:8082"
